import js from "@eslint/js";
import jsxA11y from "eslint-plugin-jsx-a11y";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: [
      "**/dist/**",
      "**/.next/**",
      "**/node_modules/**",
      "**/generated/**",
      // Generated by `pnpm generate` (@atproto/lex) — not our code style to enforce.
      "**/lexicons/src/lexicons/**",
      // Generated by `authority regen` (packages/lexicons) — embedded artifact.
      "**/*.generated.ts",
    ],
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
  // WEB PHASE 15 — static accessibility linting. Scoped by extension
  // (`.tsx`) rather than a path prefix: this eslint.config.js is shared by
  // every workspace package, each of which runs `eslint -c ../../eslint.config.js`
  // from its OWN directory — a path-prefixed glob like "apps/web/**" fails
  // to match because flat-config `files` patterns resolve against the
  // invoking process's cwd, not this file's location. `apps/web` is the
  // only package with any `.tsx` files at all (verified: zero elsewhere in
  // the workspace), so this is equivalent in practice to scoping by package.
  {
    files: ["**/*.tsx"],
    plugins: { "jsx-a11y": jsxA11y },
    rules: jsxA11y.flatConfigs.recommended.rules,
  },
);
