import "server-only";

import {
  ALL_NSIDS,
  AUTHORITY_CAR,
  AUTHORITY_DID_DOCUMENT,
  AUTHORITY_MANIFEST,
  AUTHORITY_RECORDS,
  LEXICON_AUTHORITY_DID,
  LEXICON_SCHEMA_COLLECTION,
  schemaRecordUri,
} from "@foryour-fans/lexicons/authority";

/**
 * The `fans.foryour.*` Lexicon authority's served read surface.
 *
 * `did:web:foryour.fans` resolves to this origin (the web app), so the DID
 * document and the minimal signed schema repo are served from here — NOT from
 * apps/api. This surface exposes ONLY the `com.atproto.lexicon.schema`
 * collection. No writes, no auth, no app state, no proxying (Non-negotiable
 * Rule 4). Everything it returns is a committed artifact from
 * `@foryour-fans/lexicons` (regenerated by `authority regen`).
 *
 * Design + protocol research: `docs/lexicon-authority.md`. The canonical
 * resolver (`@atproto/lex-resolver`) uses `com.atproto.sync.getRecord` + a
 * signed-commit/MST proof; the `com.atproto.repo.*` JSON routes are for lenient
 * clients (`goat`, `curl`) only.
 */

const COLLECTION = LEXICON_SCHEMA_COLLECTION;
const MANIFEST = AUTHORITY_MANIFEST as unknown as {
  did: string;
  commitCid: string;
  rev: string;
  records: Record<string, string>;
};

const CACHE_CONTROL = "public, max-age=300";
const CORS_HEADERS: Record<string, string> = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, OPTIONS",
  "access-control-allow-headers": "*",
};

function json(body: unknown, init?: { status?: number; cache?: boolean }): Response {
  return new Response(JSON.stringify(body), {
    status: init?.status ?? 200,
    headers: {
      "content-type": "application/json; charset=utf-8",
      ...(init?.cache === false ? {} : { "cache-control": CACHE_CONTROL }),
      ...CORS_HEADERS,
    },
  });
}

/** atproto error envelope. */
function xrpcError(error: string, message: string, status: number): Response {
  return json({ error, message }, { status, cache: false });
}

export function corsPreflight(): Response {
  return new Response(null, { status: 204, headers: CORS_HEADERS });
}

// --- /.well-known/did.json -------------------------------------------------

export function didDocumentResponse(): Response {
  return new Response(JSON.stringify(AUTHORITY_DID_DOCUMENT, null, 2) + "\n", {
    status: 200,
    headers: {
      // The did:web resolver accepts application/json or application/did+ld+json
      // (charset param is stripped before matching).
      "content-type": "application/did+ld+json",
      "cache-control": CACHE_CONTROL,
      ...CORS_HEADERS,
    },
  });
}

// --- /xrpc/<method> ------------------------------------------------------------

function carResponse(): Response {
  return new Response(new Uint8Array(AUTHORITY_CAR), {
    status: 200,
    headers: {
      "content-type": "application/vnd.ipld.car",
      "cache-control": CACHE_CONTROL,
      ...CORS_HEADERS,
    },
  });
}

function checkRepoParam(value: string | null): Response | null {
  // Accept the authority DID, or a bare-hostname form some tools pass; reject
  // anything else — this repo only serves one identity.
  if (value && value !== MANIFEST.did && value !== LEXICON_AUTHORITY_DID) {
    return xrpcError("InvalidRequest", `This is the ${MANIFEST.did} Lexicon authority; unknown repo "${value}"`, 400);
  }
  return null;
}

function checkCollectionParam(value: string | null): Response | null {
  if (value && value !== COLLECTION) {
    return xrpcError("InvalidRequest", `Only the ${COLLECTION} collection is served here`, 400);
  }
  return null;
}

export function xrpcResponse(method: string, url: URL): Response {
  const params = url.searchParams;

  switch (method) {
    case "com.atproto.sync.getRecord": {
      const bad =
        checkRepoParam(params.get("did")) ?? checkCollectionParam(params.get("collection"));
      if (bad) return bad;
      const rkey = params.get("rkey");
      if (!rkey) return xrpcError("InvalidRequest", "rkey is required", 400);
      if (!ALL_NSIDS.includes(rkey)) {
        return xrpcError("RecordNotFound", `No lexicon schema record for "${rkey}"`, 404);
      }
      // The whole authority CAR proves any single record (the resolver
      // MST-walks to collection/rkey). It is a few KB.
      return carResponse();
    }

    case "com.atproto.sync.getRepo": {
      const bad = checkRepoParam(params.get("did"));
      if (bad) return bad;
      return carResponse();
    }

    case "com.atproto.sync.listRepos": {
      return json({
        repos: [{ did: MANIFEST.did, head: MANIFEST.commitCid, rev: MANIFEST.rev, active: true, status: null }],
      });
    }

    case "com.atproto.sync.getLatestCommit": {
      const bad = checkRepoParam(params.get("did"));
      if (bad) return bad;
      return json({ cid: MANIFEST.commitCid, rev: MANIFEST.rev });
    }

    case "com.atproto.repo.describeRepo": {
      const bad = checkRepoParam(params.get("repo"));
      if (bad) return bad;
      return json({
        did: MANIFEST.did,
        handle: MANIFEST.did,
        handleIsCorrect: false,
        didDoc: AUTHORITY_DID_DOCUMENT,
        collections: [COLLECTION],
      });
    }

    case "com.atproto.repo.getRecord": {
      const bad =
        checkRepoParam(params.get("repo")) ?? checkCollectionParam(params.get("collection"));
      if (bad) return bad;
      const rkey = params.get("rkey");
      if (!rkey) return xrpcError("InvalidRequest", "rkey is required", 400);
      if (!ALL_NSIDS.includes(rkey)) {
        return xrpcError("RecordNotFound", `No lexicon schema record for "${rkey}"`, 404);
      }
      return json({
        uri: schemaRecordUri(rkey, MANIFEST.did),
        cid: MANIFEST.records[rkey],
        value: AUTHORITY_RECORDS[rkey],
      });
    }

    case "com.atproto.repo.listRecords": {
      const bad =
        checkRepoParam(params.get("repo")) ?? checkCollectionParam(params.get("collection"));
      if (bad) return bad;
      return json({
        records: ALL_NSIDS.map((nsid) => ({
          uri: schemaRecordUri(nsid, MANIFEST.did),
          cid: MANIFEST.records[nsid],
          value: AUTHORITY_RECORDS[nsid],
        })),
      });
    }

    default:
      return xrpcError(
        "MethodNotImplemented",
        `The ${MANIFEST.did} Lexicon authority serves only com.atproto.{sync,repo}.* reads for ${COLLECTION}`,
        404,
      );
  }
}
